apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.global.mainChartName }}
    labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app: {{ .Chart.Name }}
type: Opaque
data:
    storageAccountName: {{ b64enc .Values.storageAccountName }}
    storageAccountKey: {{ b64enc .Values.storageAccountKey }}
    eventHubReaderPath: {{ b64enc .Values.eventHubReaderPath }}
    eventHubReaderConnectionString: {{ b64enc .Values.eventHubReaderConnectionString }}
    eventHubSenderConnectionString: {{ b64enc .Values.eventHubSenderConnectionString }}