apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}
    labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: cache
spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}