apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: {{ .Chart.Name }}
    labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: frontend
spec:
    replicas: {{ .Values.replicas }}
    template:
        metadata:
            name: {{ .Chart.Name }}
            labels:
                app: {{ .Chart.Name }}
                release: {{ .Release.Name }}
        spec:
            containers:
              - name: {{ .Chart.Name }}
                image: "{{ .Values.global.imageRepository }}/{{ .Chart.Name }}:latest"
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
            imagePullSecrets:
              - name: {{ .Values.global.imagePullSecret }}